(deftheme candy
  "Created 2011-11-22.")

(custom-theme-set-variables
 'candy
 '(custom-safe-themes (quote ("236c4850ebd29e4232cad433066747ccd585faf5" default))))

(custom-theme-set-faces
 'candy
 '(default ((t (:background "#000000" :foreground "#eeeeec"))))
 '(ack-match ((t (:background "black" :foreground "gold" :underline (:color foreground-color :style line) :weight bold))))
 '(ahg-status-unknown-face ((t (:foreground "dark gray"))))
 '(column-marker-1 ((t (:background "gray11" :underline "OrangeRed4"))))
 '(cursor ((((class color) (min-colors 89)) (:background "#fce94f"))))
 '(diff-added ((t (:inherit diff-changed :foreground "yellow green"))))
 '(diff-file-header ((t (:inherit diff-header :weight bold))))
 '(diff-header ((t (:background "grey10"))))
 '(diff-removed ((t (:inherit diff-changed :foreground "OrangeRed4"))))
 '(ediff-current-diff-A ((((class color) (min-colors 89)) (:background "#555753"))))
 '(ediff-current-diff-B ((((class color) (min-colors 89)) (:background "#555753"))))
 '(ediff-even-diff-A ((((class color) (min-colors 89)) (:background "#41423f"))))
 '(ediff-even-diff-B ((((class color) (min-colors 89)) (:background "#41423f"))))
 '(ediff-fine-diff-A ((((class color) (min-colors 89)) (:background "#204a87"))))
 '(ediff-fine-diff-B ((((class color) (min-colors 89)) (:background "#8f5902"))))
 '(ediff-odd-diff-A ((((class color) (min-colors 89)) (:background "#41423f"))))
 '(ediff-odd-diff-B ((((class color) (min-colors 89)) (:background "#41423f"))))
 '(error ((((class color) (min-colors 89)) (:foreground "#ff4b4b"))))
 '(escape-glyph ((((class color) (min-colors 89)) (:foreground "#c4a000"))))
 '(fixed-pitch ((t (:family "Ubuntu Mono"))))
 '(flyspell-duplicate ((((class color) (min-colors 89)) (:underline "#fcaf3e"))))
 '(flyspell-incorrect ((((class color) (min-colors 89)) (:underline "#ef2929"))))
 '(font-latex-sectioning-2-face ((t (:inherit font-latex-sectioning-3-face :height 1.0))))
 '(font-latex-sectioning-3-face ((t (:inherit font-latex-sectioning-4-face :height 1.0))))
 '(font-latex-sectioning-4-face ((t (:inherit font-latex-sectioning-5-face :height 1.0))))
 '(font-lock-builtin-face ((t (:foreground "tan3"))))
 '(font-lock-comment-face ((t (:foreground "dark gray"))))
 '(font-lock-constant-face ((t (:inherit font-lock-variable-name-face :weight bold))))
 '(font-lock-function-name-face ((t (:foreground "#EDD400"))))
 '(font-lock-keyword-face ((t (:foreground "light sky blue"))))
 '(font-lock-string-face ((t (:foreground "yellow green"))))
 '(font-lock-type-face ((((class color) (min-colors 89)) (:foreground "#8cc4ff"))))
 '(font-lock-variable-name-face ((((class color) (min-colors 89)) (:foreground "#fcaf3e"))))
 '(font-lock-warning-face ((t (:inherit error :box (:line-width 1 :color "dark red")))))
 '(fringe ((((class color) (min-colors 89)) (:background "#212526"))))
 '(gnus-group-mail-1 ((((class color) (min-colors 89)) (:foreground "#ad7fa8"))))
 '(gnus-group-mail-1-low ((((class color) (min-colors 89)) (:foreground "#75507b"))))
 '(gnus-group-mail-2 ((((class color) (min-colors 89)) (:foreground "#729fcf"))))
 '(gnus-group-mail-2-low ((((class color) (min-colors 89)) (:foreground "#3465a4"))))
 '(gnus-group-mail-3 ((((class color) (min-colors 89)) (:foreground "#8ae234"))))
 '(gnus-group-mail-3-empty ((t (:foreground "dark gray"))) t)
 '(gnus-group-mail-3-low ((((class color) (min-colors 89)) (:foreground "#73d216"))))
 '(gnus-group-mail-low ((((class color) (min-colors 89)) (:foreground "#edd400"))))
 '(gnus-group-news-1 ((((class color) (min-colors 89)) (:foreground "#ad7fa8"))))
 '(gnus-group-news-1-low ((((class color) (min-colors 89)) (:foreground "#75507b"))))
 '(gnus-group-news-2 ((((class color) (min-colors 89)) (:foreground "#729fcf"))))
 '(gnus-group-news-2-low ((((class color) (min-colors 89)) (:foreground "#3465a4"))))
 '(gnus-group-news-3 ((((class color) (min-colors 89)) (:foreground "#8ae234"))))
 '(gnus-group-news-3-empty ((t (:foreground "dark gray"))) t)
 '(gnus-group-news-3-low ((((class color) (min-colors 89)) (:foreground "#73d216"))))
 '(gnus-group-news-4 ((((class color) (min-colors 89)) (:foreground "#e6a8df"))))
 '(gnus-group-news-4-low ((((class color) (min-colors 89)) (:foreground "#c17d11"))))
 '(gnus-group-news-5 ((((class color) (min-colors 89)) (:foreground "#fcaf3e"))))
 '(gnus-group-news-5-low ((((class color) (min-colors 89)) (:foreground "#f57900"))))
 '(gnus-group-news-low ((((class color) (min-colors 89)) (:foreground "#edd400"))))
 '(gnus-header-content ((((class color) (min-colors 89)) (:weight normal :foreground "#c4a000"))))
 '(gnus-header-from ((((class color) (min-colors 89)) (:foreground "#edd400"))))
 '(gnus-header-name ((((class color) (min-colors 89)) (:foreground "#729fcf"))))
 '(gnus-header-newsgroups ((((class color) (min-colors 89)) (:foreground "#c17d11"))))
 '(gnus-header-subject ((((class color) (min-colors 89)) (:foreground "#8ae234"))))
 '(highlight ((t (:background "gray14"))))
 '(isearch ((((class color) (min-colors 89)) (:foreground "#eeeeec" :background "#ce5c00"))))
 '(lazy-highlight ((((class color) (min-colors 89)) (:background "#8f5902"))))
 '(link ((((class color) (min-colors 89)) (:underline t :foreground "#729fcf"))))
 '(link-visited ((((class color) (min-colors 89)) (:underline t :foreground "#3465a4"))))
 '(message-cited-text ((((class color) (min-colors 89)) (:foreground "#8ae234"))))
 '(message-header-cc ((((class color) (min-colors 89)) (:foreground "#c4a000"))))
 '(message-header-name ((((class color) (min-colors 89)) (:foreground "#729fcf"))))
 '(message-header-other ((((class color) (min-colors 89)) (:foreground "#c17d11"))))
 '(message-header-subject ((((class color) (min-colors 89)) (:foreground "#8ae234"))))
 '(message-header-to ((((class color) (min-colors 89)) (:foreground "#edd400"))))
 '(message-separator ((((class color) (min-colors 89)) (:foreground "#ad7fa8"))))
 '(minibuffer-prompt ((((class color) (min-colors 89)) (:foreground "#b4fa70"))))
 '(mode-line ((t (:background "#2e3436" :foreground "#d3d7cf" :box nil))))
 '(mode-line-inactive ((t (:inherit mode-line :background "#212526" :foreground "dim gray" :box nil :weight light))))
 '(monky-diff-add ((t (:foreground "olive drab"))))
 '(org-agenda-done ((t (:foreground "dim gray"))) t)
 '(org-document-title ((t (:foreground "white" :weight bold :height 1.0))))
 '(org-scheduled ((t (:foreground "chartreuse"))))
 '(org-scheduled-today ((t (:foreground "gray"))))
 '(persp-selected-face ((t (:foreground "olive drab" :weight bold))))
 '(py-XXX-tag-face ((t (:foreground "dark orange"))))
 '(pycomplexity-complexity-high ((t (:background "#660000" :foreground "#660000"))))
 '(pycomplexity-complexity-low ((t (:background "#2A4C08" :foreground "#2A4C08"))))
 '(pycomplexity-complexity-normal ((t (:background "#7f7200" :foreground "#7f7200"))))
 '(region ((((class color) (min-colors 89)) (:background "#555753"))))
 '(rst-level-1-face ((t (:background "black" :weight bold))) t)
 '(rst-level-2-face ((t (:background "black" :weight bold))) t)
 '(rst-level-3-face ((t (:background "black" :weight bold))) t)
 '(secondary-selection ((((class color) (min-colors 89)) (:background "#204a87"))))
 '(semantic-decoration-on-includes ((((class color) (min-colors 89)) (:underline "#888a85"))))
 '(semantic-decoration-on-private-members-face ((((class color) (min-colors 89)) (:background "#5c3566"))))
 '(semantic-decoration-on-protected-members-face ((((class color) (min-colors 89)) (:background "#8f5902"))))
 '(semantic-decoration-on-unknown-includes ((((class color) (min-colors 89)) (:background "#a40000"))))
 '(semantic-decoration-on-unparsed-includes ((((class color) (min-colors 89)) (:background "#41423f"))))
 '(semantic-tag-boundary-face ((((class color) (min-colors 89)) (:overline "#729fcf"))))
 '(semantic-unmatched-syntax-face ((((class color) (min-colors 89)) (:underline "#ef2929"))))
 '(simple-rtm-task-duedate-due ((t (:inherit simple-rtm-task :background "dark red" :foreground "gainsboro"))))
 '(smerge-refined-change ((((class color) (min-colors 89)) (:background "#204a87"))))
 '(success ((((class color) (min-colors 89)) (:foreground "#8ae234"))))
 '(trailing-whitespace ((((class color) (min-colors 89)) (:background "#a40000"))))
 '(variable-pitch ((t (:family "Ubuntu Mono"))))
 '(warning ((((class color) (min-colors 89)) (:foreground "#fcaf3e"))))
 '(window-number-face ((t (:inherit modeline-emphasis :foreground "lightyellow3"))))
;; '(highlight ((((class color) (min-colors 89)) (:foreground "#2e3436" :background "#edd400"))))
)

(provide-theme 'candy)
